# This is the configuration used to check the rubocop source code.
AllCops:
  RunRailsCops: true

  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Documentation:
  Enabled: false
